version: "3"
services:
  redis:
    image: redis
    networks: 
      - webnet
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks: 
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: slack
    ports:
      - "3030:5432"
  web:
    image: benawad/slack-clone-server:latest
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      SERVER_URL: http://ec2-13-57-213-163.us-west-1.compute.amazonaws.com
    volumes:
      - ./files:/app/files
    depends_on:
      - db
      - redis
    # command: ["./wait-for-it.sh", "db:5432", "--", "node", "index.js"]
    command: ["node", "index.js"]
  nginx:
    image: nginx
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
      - ./files:/files
    ports:
      - "80:80"
    networks:
      - webnet
    depends_on:
      - web
    command: /bin/bash -c "cat /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
networks:
  webnet: